### ISSUE TITLE
Same Video downloaded via LFS of 3 capture dirs.

### ISSUE THREAD

**Issue by wlf-darkmatter** [GTEC-UDC/citic-mtmc-dataset#1]
I have download the whole project with command `git lfs clone https://github.com/GTEC-UDC/citic-mtmc-dataset.git`. And I'm sure I have **`git-lfs`** installed.
May I ask that, are there **three different video** in **three capture dirs**? Since I figured out that the videos in `capture1`, `capture2` and `capture3`  have no difference with each others except the _number of video duration_. But the real content and length of these videos are the same.

**Comment by angelcarro** [comment]
There is different content in each capture. However, the path followed by each individual is almost the same. This was done to test the semi-automated method of generating the dataset ground-truth.
